export const iconNames = [
  'ArrowDownOutlined',
  'ArrowUpOutlined',
  'CheckCircleFilled',
  'CloseCircleFilled',
  'CloseCircleOutlined',
  'DownOutlined',
  'ExclamationCircleFilled',
  'EyeInvisibleOutlined',
  'EyeOutlined',
  'InfoCircleFilled',
  'LoadingOutlined',
  'SearchOutlined',
  'UserOutlined',
]
